application: 4mapper
version: r12
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /.*
  script: code.py

